name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        default: patch
jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      version: ${{ inputs.version }}
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.PUSH_ID }}
          private-key: ${{ secrets.PUSH_KEY }}
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ steps.generate-token.outputs.token }}
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Create release commit and tags
        shell: bash
        run: |
          full_version="$(npm version "$version" --no-git-tag-version)"
          major_version="$(echo "$full_version" | cut -d. -f1)"
          npm install
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json package-lock.json
          git commit -m "chore(release): ${full_version} [skip ci]"
          git tag "${full_version}"
          git tag "v$major"
          echo "full_version=${full_version}" >> "$GITHUB_ENV"
          echo "major_version=${major_version}" >> "$GITHUB_ENV"
      - name: Push commit and tags
        shell: bash
        run: |
          git push --atomic origin main "${full_version}" "+${major_version}"
      - name: Create release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh release create "${full_version}" \
            --title "${full_version}" \
            --notes "Release ${full_version}" \
            --target "$(git rev-parse HEAD)"
